name: webool_test
description: "A new Flutter project."
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.2.5 <4.0.0"
dependencies:
  webool_network:
    path: ../packages/webool_network
  webool_common:
    path: ../packages/webool_common

  flutter:
    sdk: flutter
  go_router: ^14.2.0
  riverpod: ^2.1.3
  cupertino_icons: ^1.0.2
  dimensions_theme: ^0.0.2+1
  flutter_riverpod: ^2.1.3
  flutter_screenutil: ^5.6.0
  dropdown_search: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  mockito: ^5.0.7  

flutter:
  uses-material-design: true
