name: webool_test
description: "A new Flutter project."
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.2.5 <4.0.0"
dependencies:
  webool_network:
    path: ../packages/webool_network    # webool_network is used to get endpoints of server and handling netowrk calls
  webool_common:
    path: ../packages/webool_common    # webool_common is used to contain common theme, widgets and otehr general purpose utils

  flutter:
    sdk: flutter
  go_router: ^14.2.0  # go_router used for routing management 
  riverpod: ^2.1.3     # riverpod is used for state management
  cupertino_icons: ^1.0.2
  dimensions_theme: ^0.0.2+1  # dimentions_Ttheme used to maintain common padding marging and other dimention related functiosn
  flutter_riverpod: ^2.1.3  
  flutter_screenutil: ^5.6.0  # screen util is required to used dimentions_theme 
  dropdown_search: ^5.0.6      # used for searchble dropdown
  floor: ^1.5.0                # used for local database managmeent

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  mockito: ^5.0.7  
  floor_generator: ^1.2.0

flutter:
  uses-material-design: true
