name: webool_network
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  dartz: ^0.10.1
  freezed_annotation: ^2.2.0  
  #equatable: ^2.0.5

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4
